train: False

gpu_number: '0'

training_img_root: ''
validation_img_root: ''

# Training settings
resume: False
save_weights: False
save_weights_path: ''
save_training_stats: False

# Training hyperparameters
learning_rate: 0.0001
beta_1: 0.9
beta_2: 0.999
epochs: 200
batch_size: 128
model_weights_path: ''







